### ISSUE TITLE
Document Motivation Behind "New" Workbench Style

### ISSUE THREAD

**Issue by gbroques** [FreeCAD/freecad.workbench_starterkit#10]
There's a nice mention about the "old" style of workbenches in the **README** under **Additional Information**:

> old_style_module: A package which is plugged into FreeCAD by adding it's base-directory to sys.path and uses **Init.py** and **InitGui.py** to get initialized by FreeCAD.

However, it's not crystal-clear to me **why** you would want to switch from the "old" style to the "new" style.

What's the motivation to switch, and key differences between both styles?

@looooo Has discussed this disparately throughout the forum, but it'd be nice to have a concise and clear article somewhere.

---

I can start to collect the motivation behind the new style from forum threads.

### Pros of New Style

1. "[If] someone writes a macro for FreeCAD and wants to run it with python. Ideally, this just works." (i.e. there are compatibility issues with writing workbenches and macros for FreeCAD and using them outside of FreeCAD in "pure" python)
    * [Source](https://forum.freecadweb.org/viewtopic.php?f=8&t=40749&hilit=new+old+workbench+starterkit#p346331)
2. Name-spaced packages avoid namespace collisions and the need to have a common prefix on all classes and files to ensure uniqueness.
    * [Source](https://forum.freecadweb.org/viewtopic.php?f=23&t=38593&p=345439&hilit=new+old+workbench+starterkit#p345437)
3. Integrating with PyPI / `pip`. The ability to `pip install freecad.myworkbench`.
    * [Source](https://forum.freecadweb.org/viewtopic.php?f=10&t=38476&p=326444&hilit=workbench+starterkit#p326574)

### Cons of New Style
1. Incompatible with FreeCAD 16
    * Backwards compatibility issues in general 
---

I'm currently involved in a project where I have to support FreeCAD 16 workbenches, and there's resistance behind upgrading to a later FreeCAD version.

Having more information about the advantages of the "new" style would be very helpful.

**Comment by looooo** [comment]
We cannot fully move towards new-style because of python2-support is still ongoing. The problem here is a combination of addon-manager / namespace-packages / how freecad is maintained for several distros. There is a little difference between py2 namespace-packages and py3-namespace packages.

You already mentioned the main cons and pros. There are also other pros (like using `__file__` in a iinit_gui.py which is caused by using `exec` to initialize the workbenches and using `exec` for this task is known to be bad-practise ...)

**Comment by looooo** [comment]
@gbroques can you make a PR and add the PROS. The incompatibility with older freecad versions was already added.

**Comment by gbroques** [comment]
@looooo Sure thing, not a problem.

I should be able to toss something up within the next day or two.
